codecov:
  require_ci_to_pass: yes
  max_report_age: 24

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        paths:
          - "labs/"
          - "scripts/"
          - "mongodb-faker-generator/"

    patch:
      default:
        target: 80%
        threshold: 1%

    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

flags:
  nodejs-labs:
    paths:
      - labs/**/*.js
    carryforward: true

  python-faker:
    paths:
      - mongodb-faker-generator/**/*.py
    carryforward: true

  python-scripts:
    paths:
      - scripts/**/*.py
    carryforward: true

ignore:
  - "**/node_modules/**/*"
  - "**/venv/**/*"
  - "**/tests/**/*"
  - "**/__pycache__/**/*"
  - "**/coverage/**/*"
  - "**/dist/**/*"
  - "**/*.test.js"
  - "**/*.spec.js"
  - "**/test_*.py"